PrestaShopCorp/ps_mbo

controllers/admin/AdminPsMboModuleController.php

Fix error with object given to shuffle()

---

.gitignore
classes/Addons.php
classes/index.php
controllers/admin/AdminPsMboModuleController.php
controllers/admin/AdminPsMboThemeController.php
controllers/admin/index.php
controllers/index.php
index.php
ps_mbo.php
views/css/controllers/index.php
views/css/controllers/module/index.php
views/css/index.php
views/fonts/index.php
views/img/index.php
views/index.php
views/js/controllers/index.php
views/js/controllers/module/index.php
views/js/controllers/module/search.js
views/js/index.php
views/templates/admin/controllers/index.php
views/templates/admin/include/index.php
views/templates/admin/index.php
views/templates/admin/page.tpl
views/templates/index.php

Please check if everything is ok about dynamic routing, to prevent routing change from the Core.
I fix all license, run cs fixer and indentation problems.

Refactoring

---

views/css/controllers/module/module.css

Css on product card

---

views/js/controllers/module/search.js

Fix #54 - Configure link after install

---

views/PrestaShop/Admin/Module/Includes/grid_manage_empty.html.twig

Fixes https://github.com/PrestaShop/PrestaShop/issues/11247

Remove unused category object from template

---

views/css/controllers/module/module.css
views/js/controllers/module/module_card.js
views/templates/admin/page.tpl

Try to fix css and remove absolute.

Try to fix css

---

config.xml
ps_mbo.php

Update version to 1.1.1

---

.php-cs-fixer.dist.php
.php_cs.dist
composer.lock

Update php-dev-tools librabry along with other composer dependencies.

Update PHP Dev tools and bump other packages

---

src/Traits/UseHooks.php

The button which open modals with recommended modules was missing due to a call only to the method `shouldDisplayAfterContent` when checking if we need to display or not recommendations.
This was introduced on the global refactoring of this module for the v3

Re-add recommended modules button on several pages.

---

config/routes.yml
config/routes/addons.yml
config/routes/modules_catalog.yml
config/routes/recommended_modules.yml
config/routes/theme_catalog.yml

| Branch?           | 3.x
| Description?      | Split `routes.yml` file in subfiles per page/functionality.
| Type?             | refacto 
| How to test?      | Pages (Themes & Modules catalog) and login to addons need to work as expected.

Split routes into multiple files

---

src/Traits/Hooks/UseDashboardZoneTwo.php

| Branch?           | 3.x
| Description?      | Fix an undefined variable in tpl
| Type?             | fix
| Fixes | [#MBO-101](https://forge.prestashop.com/browse/MBO-101)
| How to test?      | Browse dashboard page after installing MBO module, the warning should not appear

[MBO-101] Fix undefined variable in tpl

---

src/Traits/Hooks/UseAdminModuleExtraToolbarButton.php

Update linked to https://github.com/PrestaShop/PrestaShop/pull/27485#pullrequestreview-911226257

Return an ActionsBarButtonsCollection when retrieving extraToolBarButtons

---

config/services.yml
src/Controller/Admin/AddonsController.php
src/RecommendedModule/RecommendedModule.php
src/RecommendedModule/RecommendedModuleInterface.php

Also removed the `$modulesDataProvider` as it's never used.

Change the namespace after core update

---

config/services.yml
src/Addons/Provider/LinksProvider.php
src/Controller/Admin/ModuleRecommendedController.php
views/templates/admin/controllers/module_catalog/recommended-modules.html.twig

TO have the correct link in all languages.
Maybe this is a correct solution to handle translated links ?
What do you think @sowbiba  ?

[MBO-152] Correctly translate the addons link for carriers & payment

---

src/Addons/Provider/LinksProvider.php
src/Controller/Admin/ModuleRecommendedController.php
src/Traits/Hooks/UseDashboardZoneTwo.php
src/Traits/Hooks/UseDisplayBackOfficeEmployeeMenu.php
views/templates/hook/dashboard-zone-two.tpl

The #159 is needed to be merged before :)
Just translate all the links because for example : 
EN => `https://addons.prestashop.com/en/3-templates-prestashop`
FR => `https://addons.prestashop.com/fr/3-themes-prestashop`
ES => `https://addons.prestashop.com/es/3-temas-prestashop`
and so on.

[MBO-138] Translate all the links

---

ps_mbo.php
src/Traits/Hooks/UseGetAdminToolbarButtons.php

Change introduced in https://github.com/PrestaShop/PrestaShop/pull/27485

[MBO-121] Rename hook AdminModuleExtraToolbarButton to GetAdminToolbarButtons

---

ps_mbo.php
src/Traits/Hooks/UseDisplayBackOfficeEmployeeMenu.php
src/Traits/Hooks/UseGetAdminToolbarButtons.php

SOme fixes introduced by https://github.com/PrestaShop/PrestaShop/pull/27485/commits/8962136813325f48d96343908c15fcd557b7c874

[MBO-121] Rename hook to display toolbar buttons + some fixes

---

src/Module/ModuleBuilder.php
src/Module/Repository.php

`shop_active` is checked in the wrong `$result`object.
Remove useless test (already tested 5 lines before)

[MBO-154] Fix actions in dropdown after install

---

src/Traits/Hooks/UseDisplayBackOfficeEmployeeMenu.php
src/Traits/Hooks/UseGetAdminToolbarButtons.php

Do not merge before https://github.com/PrestaShop/PrestaShop/pull/27485

Fix namespace for ActionsBar classes

---

config/services.yml
ps_mbo.php
src/Addons/Provider/LinksProvider.php
src/Traits/Hooks/UseDisplayEmptyModuleCategoryExtraMessage.php
views/templates/hook/twig/module_manager_empty_category.html.twig

Have to wait for https://github.com/PrestaShop/PrestaShop/pull/28318

[MBO-81] Display a message when modules category is empty

---

ps_mbo.php
src/Traits/HaveTabs.php
src/Traits/Hooks/UseActionAdminControllerSetMedia.php
src/Traits/Hooks/UseActionBeforeInstallModule.php
src/Traits/Hooks/UseActionBeforeUpgradeModule.php
src/Traits/Hooks/UseActionDispatcherBefore.php
src/Traits/Hooks/UseActionGetAdminToolbarButtons.php
src/Traits/Hooks/UseActionGetAlternativeSearchPanels.php
src/Traits/Hooks/UseActionListModules.php
src/Traits/Hooks/UseDashboardZoneOne.php
src/Traits/Hooks/UseDashboardZoneThree.php
src/Traits/Hooks/UseDisplayDashboardTop.php
src/Traits/Hooks/UseDisplayModuleConfigureExtraButtons.php
src/Traits/UseHooks.php
upgrade/upgrade-2.0.0.php

Use an intermediary trait "UseHooks" who will deal with all hooks stuff.
Register, call methods...
Make module basefile more readable

Refacto hooks behavior to avoid use madness.

---

config/services/addons.php
config/services/cdc.yml
src/Addons/Subscriber/ModuleManagementEventSubscriber.php
src/Service/View/ContextBuilder.php
src/Service/View/InstalledModule.php

[MBO-280] Return installed modules in the CDC context

---

src/Controller/Admin/ModuleRecommendedController.php
views/js/recommended-modules.js

Remove the card when recommendation is in page.
Re-add the title & cross in the modal.

[MBO-247] Update the title ine recommendations blocks

---

src/Traits/Hooks/UseActionAdminControllerSetMedia.php
views/css/module-catalog.css

We need growl to handle notifications incoming from CDC

[MBO-279] Add growl in catalog page

---

views/js/recommended-modules.js

In the legacy pages, the modal was not correctly created.

[MBO-261] Correctly display the modal recommendation on legacy pages

---

config/services/api/modules.yml
config/services/modules.yml
src/Module/ActionsManager.php
src/Module/CommandHandler/ModuleStatusTransitionCommandHandler.php
src/Module/FilesManager.php
src/Module/Repository.php
src/Module/RepositoryInterface.php
src/Module/TransitionModule.php
src/Module/Workflow/ModuleStateMachine.php
src/Module/Workflow/TransitionsManager.php
src/Traits/Hooks/UseActionBeforeInstallModule.php
src/Traits/Hooks/UseActionBeforeUpgradeModule.php
tests/Module/Workflow/ModuleStateMachineTest.php

As we can't remove all cache from legacy, the module version will remain the old one on some static cache if we load it before.

[MBO-285] Do not build PS module instance before download the new version

---

composer.json
composer.lock
ps_mbo.php

The `loadEnv`method directly check if the .env exist and load the .dist if needed
>  * Loads a .env file and the corresponding .env.local, .env.$env and .env.$env.local files if they exist.
*
* .env.local is always ignored in test env because tests should produce the same results for everyone.
* .env.dist is loaded when it exists and .env is not found.

Use Dotenv from Symfony to perform the .env & .env.dist load

---

src/Service/View/ContextBuilder.php

For iso_code, get country from configuration, not from language

Fix: iso_code

---

.github/workflows/php.yml

Ping @PrestaShopCorp/squad-mbo-journey

PHP Syntax Check from PHP 7.2 to PHP 8.1

---

src/Traits/Hooks/UseDisplayDashboardTop.php

Relative to 
- https://forge.prestashop.com/projects/MBO/issues/MBO-329
- https://forge.prestashop.com/browse/EDIT-74
- https://github.com/PrestaShopCorp/smb_edition/pull/11
Ping @PrestaShopCorp/squad-mbo-journey

[MBO-329] Added the hook `actionMboRecommendedModules`

---

ps_mbo.php
src/Distribution/Client.php
src/Helpers/Config.php
src/Service/View/ContextBuilder.php

Waiting for endpoint in NEST Api to be able to correctly test

[MBO-390] Unregister shop when module is disabled

---

Makefile
ps_mbo.php
src/Distribution/Client.php
src/Traits/HaveShopOnExternalService.php
src/Traits/Hooks/UseActionDispatcherBefore.php
src/Traits/Hooks/UseActionObjectShopUrlUpdateAfter.php
src/Traits/UseHooks.php

Add hook to update API with new URL if change occurs.
Move some code.

[MBO-319] Listen hook when URL is updated

---

.env.integration
.env.preprod
.github/workflows/build-release.yml
composer.json
composer.lock
config/services/cdc.yml
config/services/distribution.yml
config/services/security.yml
ps_mbo.php
src/Api/Controller/AbstractAdminApiController.php
src/Api/Security/AdminAuthenticationProvider.php
src/Api/Security/AuthorizationChecker.php
src/Distribution/Client.php
src/Module/Collection.php
src/Service/View/ContextBuilder.php
src/Traits/HaveShopOnExternalService.php
src/Traits/Hooks/UseDisplayBackOfficeEmployeeMenu.php

Build & sign a JWT to give to context.
Change job to build for preprod environment

Build JWT for context & api calls

---

src/Distribution/Client.php
src/Helpers/Config.php
src/Traits/HaveShopOnExternalService.php
src/Traits/Hooks/UseActionObjectShopUrlUpdateAfter.php

Get URL from the params instead of configuration which is not updated yet

Change the way we get the URL when updating shop

---

src/Distribution/Client.php
src/Service/View/ContextBuilder.php

| Branch?           | 4.0.x / 4.x
| Description?      | We use language iso_code instead of lang
| Fixed ticket?     | Fixes MBO-435 / MBO-436 / MBO-438
| How to test?      | Menu and modules listing will be translated now

Translations fixes

---

src/Traits/Hooks/UseDisplayBackOfficeEmployeeMenu.php

| Branch?           | 4.0.x
| Description?      | The route is public now, no need to send the JWT
| Fixed ticket?     | Fixes [MBO-450](https://forge.prestashop.com/browse/MBO-450)

[MBO-450] Remove the bearer when calling getConf

---

config/routes/modules_catalog.yml
config/services.yml
src/Controller/Admin/ModuleCatalogController.php
src/Traits/Hooks/UseActionAdminControllerSetMedia.php
src/Traits/Hooks/UseActionListModules.php
views/js/catalog-see-more.js
views/templates/admin/controllers/module_catalog/includes/modal_read_more.html.twig
views/templates/admin/controllers/module_catalog/modal-read-more-content.html.twig
views/templates/hook/twig/module_manager_additional_description.html.twig

This reverts commit ad5a9621d63f61d180b6d7d53294d5af9ec9f86f.

Revert due to 500 error

---

src/Traits/Hooks/UseActionGetAdminToolbarButtons.php
views/js/addons-connector.js

Remove JS from page where it's not used

[MBO-457] fix :bug: Remove const redeclaration

---

translations/nl-NL/ModulesMboModulescatalog.nl-NL.xlf

Update NL translations for Check for updates

---

crowdin.yml

Add crowdin config file

---

crowdin.yml

Fix crowdin config file

---

crowdin.yml

Crowdin integration

---

src/Traits/Hooks/UseDisplayDashboardTop.php

| Branch?           | 4.1.x
| Description?      | Add domains to translatable strings
| Fixed ticket?     | -
| How to test?      | -

Add domains to translatable strings

---

config/services/addons.yml

https://forge.prestashop.com/browse/MBO-550

Fix :bug: Force the version to be SemVer to avoid having 1.8.0.0 parameter

---

src/Controller/Admin/AddonsController.php

Linked to https://forge.prestashop.com/browse/MBO-540

Modify Addons cookies to have httpOnly=false

---

views/templates/admin/controllers/module_catalog/cdc-error.html.twig

End of https://forge.prestashop.com/browse/MBO-271

CDC error management : Reload page

---

views/css/module-catalog.css
views/templates/admin/controllers/module_catalog/catalog.html.twig

| Branch?           | 4.1.x
| Description?      | Override the padding around the catalog and remove card style. So that the catalog can take all the available space.
| Type?             | new feature
| How to test?      | 
| Possible impacts? |

[MBO-540] Remove border in module catalog

---

src/Service/View/ContextBuilder.php

In order to let the Vue to correctly track data, add user & shop uuid in the context.
[MBO-488](https://forge.prestashop.com/browse/MBO-488)

[MBO-488] feat: :chart_with_upwards_trend: Add account information in context

---

config/services/distribution.yml
config/services/modules.yml
src/Addons/User/AddonsUser.php
src/Addons/User/UserInterface.php
src/Distribution/BaseClient.php
src/Distribution/Client.php
src/Distribution/ConnectedClient.php
src/Module/Repository.php

Some services are not loaded when installing the module.

[MBO-346] fix(Services): Separate distribution services

---

src/Controller/Admin/ModuleRecommendedController.php
src/Traits/Hooks/UseDisplayDashboardTop.php

When recommended modules are "hidden", move them in the button toolbar.

[MBO-462] feat(RecommendedModules): Stop hiding reco and move them into button

---

views/css/recommended-modules.css

Remove margin in the body, add some in the header.

style(RecommendedModules): Re-adjust layout on legay modals

---

.env.dist
.gitignore
config.xml
config/services.yml
ps_mbo.php
src/EventSubscriber/ModuleEventSubscriber.php
src/UpgradeTracker.php
upgrade/upgrade-2.0.3.php

| Branch?           | 2.0.x
| Description?      | Send tracking data to Distribution API on module MBO upgrades. This is done by upgrade script when upgrading to 2.0.3 and by subcriber for any future version
| Type?             | new feature
| Fixed ticket?     | Fixes MBO-604

[MBO-604] Track module upgrades on Distribution API

---

.github/workflows/php.yml
ps_mbo.php
src/Controller/Admin/ModuleCatalogController.php
src/Controller/Admin/ModuleSelectionController.php
tests/phpstan/phpstan-1.7.5.0.neon
tests/phpstan/phpstan-1.7.8.8.neon
tests/phpstan/phpstan-latest.neon
translations/de-DE/ModulesMboModulesselection.de-DE.xlf
translations/en-US/ModulesMboModulesselection.en-US.xlf
translations/es-ES/ModulesMboModulesselection.es-ES.xlf
translations/fr-FR/ModulesMboModulesselection.fr-FR.xlf
translations/index.php
translations/it-IT/ModulesMboModulesselection.it-IT.xlf
translations/nl-NL/ModulesMboModulesselection.nl-NL.xlf
translations/pl-PL/ModulesMboModulesselection.pl-PL.xlf
translations/pt-PT/ModulesMboModulesselection.pt-PT.xlf
translations/ru-RU/ModulesMboModulesselection.ru-RU.xlf
upgrade/upgrade-2.0.3.php

| Branch?           | 2.0.x
| Description?      | Rename Modules catalog to Marketplace and switch positions of Modules Manager and Marketplace
| Fixed ticket?     | Fixes MBO-393

[MBO-393][MBO-395] Rename modules catalog menu

---

ps_mbo.php
src/Controller/Admin/ModuleSelectionController.php
src/Traits/HaveTabs.php
src/Traits/Hooks/UseActionDispatcherBefore.php
translations/de-DE/ModulesMboModulesselection.de-DE.xlf
translations/en-US/ModulesMboModulesselection.en-US.xlf
translations/es-ES/ModulesMboModulesselection.es-ES.xlf
translations/fr-FR/ModulesMboModulesselection.fr-FR.xlf
translations/it-IT/ModulesMboModulesselection.it-IT.xlf
translations/nl-NL/ModulesMboModulesselection.nl-NL.xlf
translations/pl-PL/ModulesMboModulesselection.pl-PL.xlf
translations/pt-PT/ModulesMboModulesselection.pt-PT.xlf
translations/ru-RU/ModulesMboModulesselection.ru-RU.xlf
upgrade/upgrade-4.2.1.php

| Branch?           | 4.2..x
| Description?      | Switch Module Manager and Marketplace menus on install and upgrade + Bump version to 4.2.1
| Fixed ticket?     | Fixes MBO-641

[MBO-641] Switch Module Manager and Marketplace menus + Bump version to 4.2.1

---

ps_mbo.php

| Branch?           | 2.x
| Description?      | Upgraded ps compliance
| Type?             |  improvement
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? |

Upgraded ps compliance

---

.github/workflows/install-mydemoshop.yml

Add workflow to install module

---

.github/workflows/install-mydemoshop.yml

Use label to install on mydemoshop

---

config.xml
ps_mbo.php

feat(Version): :tag: Bump version to 2.2.1

---

src/Controller/Admin/ModuleRecommendedController.php

https://github.com/PrestaShop/PrestaShop/pull/32894 🙏🏾

[MBO-829] Redirect to Modules catalog if contextual tabClassName is not given

---

src/Service/View/ContextBuilder.php

Adding Module catalog URL & Theme catalog URL to be sure to have them everytime with the correct token. Adding PHP version for future use.

[MBO-1095] feat(Context): :sparkles: Add data in context.

---

ps_mbo.php

| Branch?           | 2.2.x
| Description?      | Upgrade PS compliance for PS 1.7.8.x
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? |

Upgrade PS compliance for PS 1.7.8.x

---

translations/en-US/ModulesMboGlobal.en-US.xlf
translations/en-US/ModulesMboLinks.en-US.xlf
translations/en-US/ModulesMboRecommendedmodulesandservices.en-US.xlf

This pull request contains the default catalogue updates introduced in the branch [fix/MBO-1249/catch-employee-email-exception]

Translation catalogue update for version fix/MBO-1249/catch-employee-email-exception 2023-09-12-09_53_54

---

src/Traits/Hooks/UseDisplayBackOfficeEmployeeMenu.php

Linked to https://github.com/PrestaShop/PrestaShop/pull/33741

Change property name from same_page to is_external_link

---

views/css/recommended-modules.css
views/js/recommended-modules.js

| Branch?           | 4.5.x
| Description?      | On SAV page the modal goes off-screen. This PR changes some of the modal's CSS properties so that it looks more like a module's detail modal.
| Type?             | bug fix 
| Fixed ticket?     | Fixes [MBO-1088](https://forge.prestashop.com/browse/MBO-1088)

[MBO-1088] Improve recommendation modal style

---

translations/en-US/ModulesMboGlobal.en-US.xlf

This pull request contains the default catalogue updates introduced in the branch [feat/MBO-1248/mbo-employee-explanation]

Translation catalogue update for version feat/MBO-1248/mbo-employee-explanation 2023-10-12-10_19_41

---

config.xml
config/services/addons.php
config/services/overrides.yml
ps_mbo.php
src/Addons/Subscriber/ModuleManagementEventSubscriber.php
src/Api/Service/ModuleTransitionExecutor.php
src/Service/MboSymfonyCacheClearer.php

[MBO-1460] [MBO 4.5.x] New way to clear cache after module actions

---

config.xml
config/routes.yml
ps_mbo.php
src/Controller/Admin/ModuleController.php
translations/de.php
translations/en.php
translations/es.php
translations/fr.php
translations/it.php
translations/nl.php
translations/pl.php
translations/pt.php
translations/ro.php
translations/ru.php
upgrade/upgrade-2.3.4.php
upgrade/upgrade-2.4.0.php
views/templates/admin/controllers/module_catalog/uninstalled-modules.html.twig

[MBO-1456] [MBO 2.4.x] Add tab for uninstalled modules in Module manager

---

ps_mbo.php
views/templates/hook/recommended-modules.tpl

[MBO-1587](https://forge.prestashop.com/browse/MBO-1587)

[MBO-1587] Add module manager message on 3.0.x

---

.github/workflows/build-release.yml
config.xml
ps_mbo.php
src/Helpers/Config.php

[MME-252] Fix/multistore default shop 3x

---

.github/workflows/build-release.yml
config.xml
ps_mbo.php
src/Helpers/Config.php
upgrade/upgrade-4.7.0.php

[MME-252] :bug: Use default shop on multishop

---

views/css/recommended-modules.css

fix : Fixe Sonar medium issue

---

src/Traits/Hooks/UseActionBeforeUpgradeModule.php

[MME-394](https://forge.prestashop.com/browse/MME-394)

[MME-394] Download module on hook before upgrade

---

.github/workflows/build-release.yml

👷 Add version in release of module

---

.github/workflows/php.yml
ps_mbo.php
tests/phpstan.sh

| Branch?           | 5.x
| Description?      | Fix module container usage, this prevents bugs from incompatibilities with the `Module::get` and I guaranties the module uses the core methods and the appropriate container
| Fixed ticket?     | ~
| How to test?      | ~
| Possible impacts? | ~

Fix module container usage

---

config/services.yml
src/Accounts/Provider/AccountsDataProvider.php

[MME-739] :bug: Fix Theme catalog page & account service load

---

src/Traits/Hooks/UseActionObjectEmployeeUpdateBefore.php

:bug: Be sure that employee given in update hook is the marketplace employee

---

src/Addons/ApiClient.php
src/Helpers/AddonsApiHelper.php
src/Module/SourceRetriever/AddonsUrlSourceRetriever.php

[MME-1002](https://forge.prestashop.com/browse/MME-1002)

[MME-1002] Add custom header on API calls

---

src/Addons/Subscriber/ModuleManagementEventSubscriber.php

[MME-1284](https://forge.prestashop.com/browse/MME-1284)
| Branch?           | 5.x

feat: add module version on shop events
