PrestaShopCorp/ps_mbo

controllers/admin/AdminPsMboModuleController.php, ps_mbo.php
The module constructor can be called anytime: during the installation, the tests and so on. On these environments, the admin context does not always exist and this makes the module failing at the admin link generation.
=> Avoid doing admin tasks in the module constructor

controllers/admin/AdminPsMboModuleController.php
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | master
| Description?  | An error was displayed in the "Themes & Logo" page, the problem was that every ajax calls in `AdminPsMboModuleController` were rendered with `ajaxProcess*` methods This resulted in updating the view before the initial header was sent causing many cascade problems afterwards (any use to Router, or access to the session resulted in an error). Since these ajax methods were used to display the page, the appropriate prefix is `displayAjax` so that they are rendered at the right time during the workflow
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes …
=> Ajax method renamed to be used in a display context as they should

ps_mbo.php
I suppose this error is due to cache, probably server cache like OPcache.
Because PrestaShop cache should be cleared on Module install in normal case.
[2020-05-28 13:01:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "mbo.tab.collection.provider"." at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php line 348 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"mbo.tab.collection.provider\". at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:348)"} []
```
Unable to generate a URL for the named route …
```
=> Avoid fatal error on ServiceNotFoundException

src/ModuleCollectionDataProvider.php
This PR aims to fix this bug : https://github.com/PrestaShop/PrestaShop/issues/21298
Because the addons API returns already escaped module descriptions, we should decode it first so it gets escaped once again in the view.
=> Prevent double escaping module descriptions

ps_mbo.php
In 1.7.6.x when you disable ps_mbo, the following menu items are still using the ps_mbo's links:
- Module Catalog
- Module Selections
- Themes Catalog
In 1.7.7.x the behavior is a bit different as it's not using ps_mbo's ones but *Themes Catalog* disapears, *Module Catalog* link is wrong and so *Module Selections* is not accessible.
This PR should fixes https://github.com/PrestaShop/PrestaShop/issues/21588
Disable ps_mbo & check that *Module Catalog*, *Module Selections* & *Themes Catalog* are still present and that their links are core's ones, not ps_mbo's.
=> Fix links when the module is disabled

views/js/recommended-modules.js
Change the selector for new layout pages in order to refer to the global layout and not depend on each controllers.
=> Update DOM selector after changes occurs on pages

.gitignore, composer.json, composer.lock, config/routes.yml, config/routes/dashboard.yml, config/services.yml, config/services/circuit_breaker.yml, config/services/news.yml, src/Controller/Admin/DashboardNewsController.php, src/Service/News/NewsDataProvider.php, src/Traits/Hooks/UseDashboardZoneThree.php, tests/phpstan/bootstrap.php, tests/phpstan/phpstan-nightly.neon, views/css/dashboard-news.css, views/js/dashboard-news.js, views/templates/hook/dashboard-zone-three.tpl
Re-implement the removed code to fetch the blog/rss data in the dashboard.
See : https://github.com/PrestaShop/PrestaShop/pull/27444#pullrequestreview-870252502
Fixes : [#MBO-25](https://forge.prestashop.com/browse/MBO-25)
=> [MBO-15] Fetch data for dashboard news

config/routes/modules_catalog.yml, src/Controller/Admin/ModuleCatalogController.php, src/Modules/ModuleBuilder.php, src/Modules/Repository.php, src/Traits/Hooks/UseAdminControllerSetMedia.php, views/css/module-catalog.css, views/js/catalog-see-more.js, views/templates/admin/controllers/module_catalog/includes/card_grid.html.twig, views/templates/admin/controllers/module_catalog/includes/card_list.html.twig, views/templates/admin/controllers/module_catalog/modal-read-more-content.html.twig
| Branch?           | 3.x
| Description?      | Get the "See more" logic button from the core to the `ps_mbo` module.
| Fixed ticket?     | [#MBO-52](https://forge.prestashop.com/browse/MBO-52)
| How to test?      | Go to the module catalog page. Click on "See more" link in module card. A modal should load (wait a second or 2)
=> [MBO-13] Add "See more" button on module cards

config/services.yml, src/Addons/User/CookieAddonsUser.php, src/Controller/Admin/AddonsController.php, src/Controller/Admin/ModuleCatalogController.php
| Branch?           | 3.x
| Description?      | When a user logs in or logs out, the modules catalog cache is cleaned because results are dependent to the connected user. We also inject services to controllers instead of using the container inside the controllers themselves
| BC breaks?        | yes
| Fixes | [#MBO-51](https://forge.prestashop.com/browse/MBO-51)
| How to test?      | -
=> [MBO-51] Clear catalog cache when user authenticate or logout. Inject services for controllers

config/services.yml, config/services/addons.php, config/services/addons.yml, ps_mbo.php, src/Addons/Subscriber/ModuleManagementEventSubscriber.php
To prevent logging events when module is not enabled, we need to register the service only when the module is truly enabled.
Is blocked by : [#27969](https://github.com/PrestaShop/PrestaShop/pull/27969)
=> [MBO-102] Load subscriber service only if module is enabled 

views/templates/admin/controllers/module_catalog/includes/tab-module-line.html.twig
The type was previously set in an obscure method on 1.7.x and override the true actual type.
I decide to switch to this behavior.
=> [MBO-150] Add the Official badge on the correct module parameter

views/templates/admin/controllers/module_catalog/recommended-modules.html.twig
If we re-click the button to open recommendation modal, we have a JS error because we try to redeclare a constant
=> Fix the const redeclaration behavior

src/Tab/Tab.php, src/Traits/Hooks/UseActionAdminControllerSetMedia.php, src/Traits/Hooks/UseDisplayDashboardTop.php
For an unknown reason, `AdminCarriers` has a wrong display type data returned by the WS.
=> [MBO-255] Correctly display recommendation in Carriers page

views/js/recommended-modules.js
Be sure to have empty content if opening again a recommendation modal.
Force the loader to be shown aswell.
The modal content is removed before the modal is open, so there is no flash of content.
=> [MBO-300] Fix the modal behavior

views/templates/hook/dashboard-zone-three.tpl
When gamification advices are retrieven, they are written after the dashboard news container. The API response for advices come with an expected selector for dashboard news : `dash_news`
This class was removed when transforming the dashboard news to CDC
This PR restores the class previously removed. It will have no effect on the block design but only used as selector
=> [MBO-94] Restore dashboard news block class

src/Module/ActionsManager.php, src/Traits/Hooks/UseActionBeforeUpgradeModule.php, src/Traits/UseHooks.php
| Branch?           | 4.0.x
| Description?      | Re add the hook to download module.. Check if the action came from back office before downloading the module
| Fixed ticket?     | [MBO-432](https://forge.prestashop.com/browse/MBO-432)
| Possible impacts? | Double-check the update from catalog to be sure that the module is not downloaded twice.
=> [MBO-432] Fix the update action from back office

src/Module/Workflow/TransitionsManager.php
| Description?      | Currently in the transitionManager it seems that we call twice the method onInstall, onUninstall... Because they are already triggered by the moduleManager. This can be the source of many errors.
| How to test?      | Try to install, uninstall, enable... some modules
=> [MBO-447] fix :zap: Stop calling twice the actions on modules

ps_mbo.php, src/Helpers/Config.php, src/Traits/HaveShopOnExternalService.php
| Branch?           | 4.0.x
| Description?      | The MBO config values (UUID, ADMIN_MAIL, ...) are cached. When resetting, we uninstall and install the module but in a same thread. That's why the values used to re-register the shop are wrong. In this PR we reset that static cache anytime the configuration values are deleted
| Fixed ticket?     | Fixes MBO-470
| How to test?      | Install MBO, display the modules catalogue. Reset the module and then go back to the modules catalogue. The page must be displayed without error
=> [MBO-470] Reset cache between uninstall and install when resetting MBO module

config/services.yml, config/services/addons.yml, src/Addons/Provider/AddonsDataProvider.php, src/Addons/User/AddonsUser.php, src/Addons/User/CredentialsEncryptor.php, src/Api/Service/ModuleTransitionExecutor.php, src/Controller/Admin/AddonsController.php, src/Module/CommandHandler/ModuleStatusTransitionCommandHandler.php
| Branch?           | 4.1.x
| Description?      | Change the way to encrypt addons credentials when user authenticates. MBO API can now receive addons credentials and forward them when requesting Addons API. That authentication is only available during the request
| Type?             | new feature
| BC breaks?        | yes
| Fixed ticket?     | Fixes MBO-540 / MBO-556 and MBO-541 / MBO-564
| How to test?      | -
| Possible impacts? | -
=> [MBO-540][MBO-541] Change encryption for addons credentials + handle authentification on API requests

config/services/addons.yml, src/Addons/Listener/AddonsCredentialsEncryptionListener.php, src/Addons/User/CredentialsEncryptor.php, src/Traits/Hooks/UseActionBeforeResetModule.php, src/Traits/UseHooks.php, upgrade/upgrade-4.2.0.php
| Branch?           | 4.2.x
| Description?      | The addons credentials are salted with the shop adminToken, encrypted and stored as cookies. When a MBO module reset is performed, that adminToken changed so it's becoming impossible to decrypt the cookies. This PR aim to decrypt and store the credentials in session before the reset; after the reset, re-encrypt them and re-store them as cookies; and then clean the values stored in clear
| Fixed ticket?     | Fixes MBO-585
| How to test?      | Log in to addons, reset MBO module. You'll remain connected
=> [MBO-585] MBO reset : Change salt of addons credential and update cookies

config.xml, ps_mbo.php, src/Traits/HaveTabs.php
| Branch?           | 4.1.x
| Description?      | On upgrade script to 4.1.0, we are using $module->updateTabs which uses the TabRepository service. During autoupgrade, service container is unavailable. That makes that usage impossible. We are now using Tab::getIdFromClassName which is not using  service container
| BC breaks?        | yes
| Fixed ticket?     | -
| How to test?      | Test MBO upgrade and PS autoupgrade
=> Avoid usage of services upgrade

src/Traits/HaveConfigurationPage.php
| Branch?           | 4.2.x
| Description?      | Following changes in the google cloud config, do not use the `latest/` sub-folder to retrieve the source code of the cdc but the `v1/` sub-folder. `latest/` is destined to disappear
| Type?             | fix on preprod deployement
=> Change cdc url on cdn for prod & preprod

src/Addons/Listener/AddonsCredentialsEncryptionListener.php
| Branch?           | 4.2.x
| Description?      | Check that action is made on MBO module before doing process on addons cookies
| Fixed ticket?     | Fixes MBO-620
| How to test?      | Install MBO, connect to addons, uninstall any other module than MBO, see that addons connection is kept
=> [MBO-620] Do not remove addons connection on all modules uninstall

src/Service/View/ContextBuilder.php
Do not transmit Accounts JWT to context to always use addons credentials. This is done to finish this feature properly
=> Do not transmit Accounts token in context

ps_mbo.php
Apparently, the addJS method does not check all JS that will be loaded on the page.
So we still have a duplicate on this one.
Actually, it seems that only the product page is broken.
| Branch?           | 2.0.x
| Description?      | Script is already loaded by the core, and create a JS error on the page which cause problems.
| Fixed ticket?     | Fixes #109
=> fix(ProductPage): Don't load module_card on Product Page

config/services/addons.php, src/Addons/Subscriber/ModuleManagementEventSubscriber.php
| Branch?           | 4.3.x
| Description?      | The Core subscriber clears Sf cache only when a module is installed or uninstalled. We need to clear it on enable/disable/enable-on-mobile/disable-on-mobile to avoid services errors
| Fixed ticket?     | Fixes MBO-728
| How to test?      | Disable MBO, Go to Orders page, you will see no error
=> [MBO-728] Clear Sf cache on module disable or enable

bootstrap.php, ps_mbo.php, src/Traits/HaveConfigurationPage.php
| Branch?           | 4.x
| Description?      | Sets default value of param `$usePutenv` explicitly on `dotenv` instances to avoid deprecation warnings.
| Fixed ticket?     | Fixes #509
| How to test?      | Enable debug mode on the shop and check _var/logs/dev.log_ file. 
| Possible impacts? | None. Just setting default value explicitly.
=> Fix deprecation about `$usePutenv`

src/Traits/Hooks/UseActionAdminControllerSetMedia.php
Controller name may not be a string in some case. Check the parameter type before calling the method
=> fix(Tabs): :bug: Be sure to call method with good parameter type

bootstrap.php
| Branch?           | 4.4.x
| Description?      | I have a problem with the module ps_mbo. If we shared the directory modules with a virtual link (on CICD for exemple), the module not working.
| Fixed ticket?     | Fixes #504
=> fix root dir

ps_mbo.php
Do not rely on tab collection from PS API but on the defined list in ps_mbo
This way, we can have modals with empty recommended modules
=> [MBO-832] Always rely on defined tabs list to display Recommended modules button

src/Addons/Provider/LinksProvider.php
| Branch?           | 4.4.x
| Description?      | There is no category Other. The category Other is to classify modules without category in Module Manager. There was a bug when you click to see more modules in Category Other so we decide to redirect to the main page of the marketplace
| Fixed ticket?     | Fixes MBO-1030
| How to test?      | Go to Module Manager, scroll to the bottom, click on See more modules on category Other. You will be redirected to the marketplace main page without category filter.<br><br>Click on another category, you will be still redirected to the marketplace with the category …
=> [MBO-1030] Do not add filterCategoryRef if category is other

src/Addons/ApiClient.php
_PS_BASE_URL_ is not defined in install process. So the domain is null
We make it optional on installation mode
=> Addons ApiClient - Make domain optional to fix PS install

README.md, config/services/modules.yml, docs/tools-update-infos.md, src/Module/Repository.php, src/Service/ModulesHelper.php
```
$this->get('mbo.modules.helper')->findForUpdates('productcomments')
```
will return
```
[
"current_version" => "5.0.2"
"available_version" => "6.0.2"
"upgrade_available" => true,
'urls' => [
'install' => null,
'upgrade' => '/manage/action/upgrade/productcomments',
]
]
```
If the module is installed and do have an upgrade
============================================================
```
[
"current_version" => "5.0.2"
"available_version" => "5.0.2"
"upgrade_available" => false,
'urls' => [
'install' => null,
'upgrade' => null,
]
]
```
If the module is installed but doesn't have an upgrade
============================================================
```
[
"current_version" => null
"available_version" => "5.0.2"
"upgrade_available" => false,
'urls' => [
'install' => …
```
=> [MBO-1524] Add service modules helper + Implement method to find updates for a module

views/templates/admin/controllers/module_catalog/catalog.html.twig, views/templates/hook/dashboard-zone-one.tpl
=> fix: remove deprecated array merge on smarty

src/Traits/Hooks/UseActionAdminControllerSetMedia.php, src/Traits/Hooks/UseDisplayDashboardTop.php
Due to the Symfony migration on certain pages, we need to ensure that recommended modules (either as buttons or inline) are displayed only on list pages.
=> :bug: Do not load recommended modules on edit or detail pages.
